SQLALCHEMY_DATABASE_URI='mysql+pymysql://thinkdb:123456@127.0.0.1:3306/fthinkdb?charset=utf8'
SQLALCHEMY_TRACK_MODIFICATIONS = True
SQLALCHEMY_POOL_SIZE = 10
SQLALCHEMY_POOL_TIMEOUT = 50
SQLALCHEMY_POOL_RECYCLE = 30
CSRF_ENABLED = True
SECRET_KEY = 'YOU-WILL-NERVER-GUESS'